### ISSUE TITLE
Dragnet Gitbook is private

### ISSUE THREAD

**Issue by wedemmoez** [tevora-threat/Dragnet#1]
I can't access the gitbook to read the documentation .

**Comment by mdalin** [comment]
Having the same issue. Just watched the Defcon presentation and this seems like a really interesting project. Would love to be able to check it out.

**Comment by trumankain** [comment]
[Fixed](https://docs.getdragnet.com/). Please let me know if anything is unclear! Working on more in-depth docs to go along with the next update. Thank you for opening/following up on this issue! I appreciate your interest @wedemmoez @mdalin @DesBlock 🙂
